import { RefreshCw, TrendingDown } from "lucide-react";
import { useEffect, useState } from "react";
const today = new Date().toISOString().slice(0, 10);
const HodAttendance = () => {
  const API_URL = import.meta.env.VITE_API_URL; const [filters, setFilters] = useState({ from: `${new Date().getFullYear()}-01-01`, to: today }); const [data, setData] = useState(null);
  const load = async () => { const response = await fetch(`${API_URL}/hod/attendance/analytics?${new URLSearchParams(filters)}`, { credentials: "include" }); setData(await response.json()); };
  useEffect(() => {
    let active = true;
    fetch(`${API_URL}/hod/attendance/analytics?${new URLSearchParams(filters)}`, { credentials: "include" })
      .then((response) => response.json())
      .then((responseData) => { if (active) setData(responseData); });
    return () => { active = false; };
  }, [API_URL, filters]);
  const totals = data?.totals || { present: 0, absent: 0, leave: 0, percentage: 0 };
  return <section className="space-y-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-cyan-600">Department intelligence</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Attendance</h1><p className="mt-1 text-sm text-slate-500">Department attendance performance and watchlist.</p></div><button onClick={load} className="inline-flex items-center justify-center gap-2 rounded-lg bg-cyan-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-cyan-700"><RefreshCw size={16} /> Refresh</button></div><div className="grid gap-3 rounded-2xl border border-slate-200 bg-linear-to-br from-white to-cyan-50/60 p-4 sm:grid-cols-2"><label className="text-xs font-semibold uppercase tracking-wide text-slate-500">From<input type="date" value={filters.from} onChange={(e) => setFilters({...filters, from:e.target.value})} className="mt-1 block w-full rounded-lg border border-slate-200 bg-white p-2.5 text-sm font-normal" /></label><label className="text-xs font-semibold uppercase tracking-wide text-slate-500">To<input type="date" value={filters.to} onChange={(e) => setFilters({...filters, to:e.target.value})} className="mt-1 block w-full rounded-lg border border-slate-200 bg-white p-2.5 text-sm font-normal" /></label></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Overall",`${totals.percentage}%`,`text-cyan-600`],["Present",totals.present,`text-emerald-600`],["Absent",totals.absent,`text-rose-600`],["Leave",totals.leave,`text-amber-600`]].map(([label,value,color])=><article key={label} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className={`mt-2 text-2xl font-bold ${color}`}>{value}</p></article>)}</div><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-2 border-b border-slate-100 p-5"><TrendingDown className="text-rose-500" size={20}/><h2 className="font-bold">Low attendance watchlist</h2></div><div className="overflow-x-auto"><table className="w-full min-w-150 text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Student</th><th className="px-5 py-3">Roll no.</th><th className="px-5 py-3">Year / Sem</th><th className="px-5 py-3">Attendance</th></tr></thead><tbody className="divide-y divide-slate-100">{data?.lowAttendance?.map((student)=><tr key={student.id}><td className="px-5 py-3 font-semibold">{student.name}</td><td className="px-5 py-3">{student.rollNumber}</td><td className="px-5 py-3">Y{student.year} / S{student.semester}</td><td className="px-5 py-3 font-bold text-rose-600">{student.percentage}%</td></tr>)}{!data?.lowAttendance?.length && <tr><td colSpan="4" className="p-10 text-center text-slate-400">No students below 75% in this period.</td></tr>}</tbody></table></div></div></section>;
};
export default HodAttendance;
